#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lsof
Version  : 4.93.2
Release  : 20
URL      : https://github.com/lsof-org/lsof/archive/4.93.2.tar.gz
Source0  : https://github.com/lsof-org/lsof/archive/4.93.2.tar.gz
Summary  : A utility which lists open files on a Linux/UNIX system
Group    : Development/Tools
License  : BSD-4-Clause
Requires: lsof-bin = %{version}-%{release}
Requires: lsof-man = %{version}-%{release}
BuildRequires : buildreq-configure
Patch1: 0001-fix-build.patch
Patch2: 0002-test-cases-include-sys-sysmaros.h-to-compile-tests-L.patch
Patch3: test.patch

%description
Lsof Binaries
I do not recommend that you use a pre-compiled lsof binary and I no
longer provide any.

%package bin
Summary: bin components for the lsof package.
Group: Binaries

%description bin
bin components for the lsof package.


%package man
Summary: man components for the lsof package.
Group: Default

%description man
man components for the lsof package.


%prep
%setup -q -n lsof-4.93.2
cd %{_builddir}/lsof-4.93.2
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582056076
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd tests
make test
make opt
popd

%install
export SOURCE_DATE_EPOCH=1582056076
rm -rf %{buildroot}
%make_install
## install_append content
mkdir -p %{buildroot}/usr/bin
mkdir -p %{buildroot}/usr/share/man/man8
install -p -m 0755 lsof %{buildroot}/usr/bin
install -p -m 0644 Lsof.8 %{buildroot}/usr/share/man/man8
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lsof

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/Lsof.8
